-- ============================================================================
-- 08_seed.sql
-- School Clinic Management System — Sample Data for Testing (MySQL)
-- ============================================================================
-- Run AFTER 07_audit.sql:
--   mysql -u root -p school_clinic < 08_seed.sql
-- ============================================================================
-- This seed data demonstrates all security features:
--   - Users across all 5 roles
--   - Students with profiles and QR codes
--   - Encrypted consultations and prescriptions
--   - Medicine dispensing records
--   - Health clearances (pending, cleared, not_cleared)
--
-- IMPORTANT: The encryption key is set as a session variable below.
-- ============================================================================

USE school_clinic;

-- ============================================================================
-- Set session variables for seed data insertion
-- ============================================================================
SET SESSION block_encryption_mode = 'aes-256-cbc';
SET @app_encryption_key = 'dev-secret-key-change-in-prod';
SET @app_current_user_id = 1;

-- ============================================================================
-- 1. USERS — All Roles
-- ============================================================================
-- Passwords are bcrypt-hashed. In this seed: all passwords are 'password123'
-- MySQL does not have pgcrypto's crypt() — hashes would be generated by
-- the application layer. Here we use a pre-computed bcrypt hash.

INSERT INTO users (username, password_hash, email, first_name, last_name, role) VALUES
    -- Admins
    ('admin',        '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'admin@school.edu',        'System',      'Administrator',  'admin'),

    -- Doctors
    ('dr.santos',    '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'santos@school.edu',       'Maria',        'Santos',         'doctor'),
    ('dr.reyes',     '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'reyes@school.edu',        'Jose',         'Reyes',          'doctor'),

    -- Nurses
    ('nurse.garcia', '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'garcia@school.edu',       'Ana',          'Garcia',         'nurse'),
    ('nurse.cruz',   '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'cruz@school.edu',         'Pedro',        'Cruz',           'nurse'),

    -- Students (user_id 6-10)
    ('juan.delacruz',  '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'juan@student.school.edu',   'Juan',        'Dela Cruz',      'student'),
    ('maria.clara',    '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'maria@student.school.edu',  'Maria Clara', 'Reyes',          'student'),
    ('andres.boni',    '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'andres@student.school.edu', 'Andres',      'Bonifacio',      'student'),
    ('gabby.silang',   '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'gabby@student.school.edu',  'Gabriela',    'Silang',         'student'),
    ('jose.rizal',     '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'jose@student.school.edu',   'Jose',        'Rizal',          'student'),

    -- Faculty (user_id 11-12)
    ('prof.luna',    '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'luna@school.edu',         'Antonio',     'Luna',           'faculty'),
    ('prof.mabini',  '$2b$12$LJ3m4ys3Lk0TSwMCfn0qTOhMFnGJGMbz8J6x5VxHbKn2iOZpZJPO', 'mabini@school.edu',       'Apolinario',  'Mabini',         'faculty');

-- ============================================================================
-- 2. STUDENTS — Extended Profiles
-- ============================================================================

-- student_number is intentionally omitted — the BEFORE INSERT trigger
-- (trg_students_before_insert) auto-assigns the YYYY-NNNN format number.
INSERT INTO students (user_id, year_of_enrollment, date_of_birth, sex, contact_number, emergency_contact_name, emergency_contact_number, year_level, section, blood_type, allergies) VALUES
    (6,  2024, '2006-03-15', 'Male',   '09171234567', 'Maria Dela Cruz',    '09181234567', 'Grade 11', 'STEM-A',  'O+',  NULL),
    (7,  2024, '2006-07-22', 'Female', '09172345678', 'Pedro Reyes',        '09182345678', 'Grade 11', 'STEM-A',  'A+',  'Penicillin'),
    (8,  2024, '2005-11-30', 'Male',   '09173456789', 'Catalina Bonifacio', '09183456789', 'Grade 12', 'HUMSS-B', 'B+',  NULL),
    (9,  2024, '2006-01-10', 'Female', '09174567890', 'Diego Silang',       '09184567890', 'Grade 11', 'ABM-A',   'AB+', 'Sulfa drugs, Ibuprofen'),
    (10, 2024, '2005-06-19', 'Male',   '09175678901', 'Teodora Alonso',     '09185678901', 'Grade 12', 'STEM-B',  'O-',  NULL);

-- ============================================================================
-- 3. QR CODES — One per Student
-- ============================================================================

INSERT INTO qr_codes (student_number) VALUES
    ('2024-0001'), ('2024-0002'), ('2024-0003'), ('2024-0004'), ('2024-0005');

-- ============================================================================
-- 4. MEDICINES — Basic Catalog
-- ============================================================================

INSERT INTO medicines (name, description, unit, available_quantity) VALUES
    ('Paracetamol 500mg',      'For fever and mild pain relief',         'tablet', 5),
    ('Ibuprofen 200mg',        'Anti-inflammatory and pain relief',      'tablet', 5),
    ('Mefenamic Acid 500mg',   'For moderate pain and dysmenorrhea',     'capsule', 5),
    ('Cetirizine 10mg',        'Antihistamine for allergies',            'tablet', 5),
    ('Loperamide 2mg',         'For acute diarrhea',                     'capsule', 5),
    ('Oral Rehydration Salts', 'For dehydration',                        'sachet', 5),
    ('Betadine Solution',      'Antiseptic for wounds',                  'ml', 5),
    ('Band-Aid',               'Adhesive bandage for minor wounds',      'piece', 5),
    ('Cotton Balls',           'For wound cleaning and dressing',        'piece', 5),
    ('Amoxicillin 500mg',      'Antibiotic (requires prescription)',     'capsule', 5);

-- ============================================================================
-- 5. CONSULTATIONS — Encrypted Medical Records
-- ============================================================================
-- Using the create_consultation procedure which auto-encrypts.

-- Consultation 1: Juan — headache and fever (attended by Nurse Garcia)
SET @app_current_user_id = 4;
CALL create_consultation(
    '2024-0001', 4,
    'Headache and fever since this morning',
    'Acute viral upper respiratory tract infection',
    'Temperature 38.5C on arrival. Given Paracetamol 500mg. Advised to rest in clinic for 30 minutes. Temperature down to 37.2C before discharge. Advised to drink plenty of fluids. Return if fever persists beyond 3 days.',
    '110/70', 38.5, 92, 58.0,
    @cid
);

-- Consultation 2: Maria Clara — allergic reaction (attended by Nurse Garcia)
CALL create_consultation(
    '2024-0002', 4,
    'Skin rashes and itching after eating seafood',
    'Allergic dermatitis — likely food allergen (seafood)',
    'Hives on forearms and neck. No respiratory distress. Given Cetirizine 10mg. Noted existing Penicillin allergy in records. Advised to avoid seafood. Rashes subsiding after 1 hour. Discharged with instructions.',
    '100/65', 36.8, 78, 50.0,
    @cid
);

-- Consultation 3: Andres — sports injury (attended by Nurse Cruz)
SET @app_current_user_id = 5;
CALL create_consultation(
    '2024-0003', 5,
    'Twisted ankle during basketball practice',
    'Grade 1 ankle sprain — lateral ligament',
    'Swelling on right lateral ankle. RICE protocol applied. Cold compress for 15 minutes. Elastic bandage wrap. Referred to Dr. Santos for further evaluation. No weight bearing advised.',
    '125/80', 36.6, 88, 68.0,
    @cid
);

-- Update consultation 3 status to 'referred'
UPDATE consultations SET status = 'referred' WHERE consultation_id = 3;

-- Consultation 4: Gabriela — menstrual cramps (attended by Nurse Garcia)
SET @app_current_user_id = 4;
CALL create_consultation(
    '2024-0004', 4,
    'Severe abdominal cramps since class started',
    'Dysmenorrhea (primary)',
    'Noted allergy to Ibuprofen — used Mefenamic Acid instead. Given Mefenamic Acid 500mg. Hot compress applied to abdomen. Rested in clinic for 45 minutes. Pain subsided from 8/10 to 3/10. Discharged.',
    '105/68', 36.9, 82, 52.0,
    @cid
);

-- Consultation 5: Jose — stomach ache (attended by Nurse Cruz)
SET @app_current_user_id = 5;
CALL create_consultation(
    '2024-0005', 5,
    'Stomach pain and nausea after lunch',
    'Acute gastritis — likely dietary cause',
    'Epigastric tenderness on palpation. No vomiting. Given ORS. Monitored for 1 hour. Symptoms improving. Advised bland diet for 24 hours. Return if symptoms worsen.',
    '118/75', 37.1, 80, 62.0,
    @cid
);

-- Consultation 6: Juan again — follow-up (attended by Nurse Garcia)
SET @app_current_user_id = 4;
CALL create_consultation(
    '2024-0001', 4,
    'Follow-up: fever resolved but still has mild cough',
    'Resolving URTI with residual cough',
    'Afebrile today. Mild productive cough. Lungs clear on auscultation. Advised to continue fluids. No medication given. Referred to Dr. Santos for prescription if cough persists.',
    '115/72', 36.7, 76, 58.0,
    @cid
);

-- Mark completed consultations
UPDATE consultations SET status = 'completed' WHERE consultation_id IN (1, 2, 4, 5);

-- ============================================================================
-- 6. PRESCRIPTIONS — Doctor-Issued (Encrypted)
-- ============================================================================

SET @app_current_user_id = 2; -- Dr. Santos

-- Prescription for Andres (ankle sprain — consultation 3)
CALL create_prescription(
    3, 2,
    'Ibuprofen 200mg — 1 tablet every 8 hours for 5 days with food. Apply cold compress 3x daily for 15 minutes.',
    'Follow up in 1 week. If swelling worsens or unable to bear weight after 48 hours, refer to orthopedic specialist. X-ray not indicated at this time.',
    @pid
);

-- Prescription for Juan (persistent cough — consultation 6)
CALL create_prescription(
    6, 2,
    'Carbocisteine 500mg — 1 capsule 3x daily for 7 days. Increase fluid intake.',
    'Cough likely post-infectious. If persists beyond 2 weeks, chest X-ray recommended.',
    @pid
);

SET @app_current_user_id = 3; -- Dr. Reyes

-- Prescription for Gabriela (dysmenorrhea — consultation 4)
CALL create_prescription(
    4, 3,
    'Mefenamic Acid 500mg — 1 capsule every 8 hours as needed for pain during menstruation. NOTE: Patient allergic to Ibuprofen.',
    'Recurring dysmenorrhea. If pain consistently >7/10, consider referral to OB-GYN for evaluation. Avoid NSAIDs containing Ibuprofen — documented allergy.',
    @pid
);

-- ============================================================================
-- 7. MEDICINES DISPENSED — Per Consultation
-- ============================================================================

INSERT INTO consultation_medicines (consultation_id, medicine_id, quantity_given, dispensed_by) VALUES
    -- Consultation 1 (Juan — fever): Paracetamol
    (1, 1, 2, 4),
    -- Consultation 2 (Maria — allergy): Cetirizine
    (2, 4, 1, 4),
    -- Consultation 3 (Andres — sprain): Ibuprofen
    (3, 2, 3, 5),
    -- Consultation 4 (Gabriela — cramps): Mefenamic Acid
    (4, 3, 2, 4),
    -- Consultation 5 (Jose — stomach): ORS
    (5, 6, 2, 5),
    -- Consultation 3 (Andres — sprain): also cotton + bandage for wrap
    (3, 8, 3, 5),
    (3, 9, 5, 5);

-- ============================================================================
-- 8. HEALTH CLEARANCES
-- ============================================================================

SET @app_current_user_id = 11; -- Prof. Luna

-- Faculty requests clearance for field trip
INSERT INTO health_clearances (student_number, purpose, requested_by) VALUES
    ('2024-0001', 'Field trip to Science Museum — March 2026',  11),
    ('2024-0002', 'Field trip to Science Museum — March 2026',  11),
    ('2024-0003', 'Field trip to Science Museum — March 2026',  11);

-- Faculty requests sports clearance
INSERT INTO health_clearances (student_number, purpose, requested_by) VALUES
    ('2024-0003', 'Interschool Basketball Tournament — April 2026', 11);

SET @app_current_user_id = 12; -- Prof. Mabini

INSERT INTO health_clearances (student_number, purpose, requested_by) VALUES
    ('2024-0005', 'School camping activity — March 2026', 12);

-- Doctor processes some clearances
SET @app_current_user_id = 2; -- Dr. Santos

UPDATE health_clearances
SET status = 'cleared', issued_by = 2, valid_until = '2026-03-31', remarks = 'Fit for participation'
WHERE clearance_id = 1;

UPDATE health_clearances
SET status = 'cleared', issued_by = 2, valid_until = '2026-03-31', remarks = 'Fit for participation. Note: patient has Penicillin allergy — ensure first aid kit has alternative medications.'
WHERE clearance_id = 2;

-- Andres not cleared for field trip (ankle sprain still recovering)
UPDATE health_clearances
SET status = 'not_cleared', issued_by = 2, remarks = 'Not cleared — recovering from Grade 1 ankle sprain. Re-evaluate in 2 weeks.'
WHERE clearance_id = 3;

-- ============================================================================
-- 9. VERIFICATION QUERIES
-- ============================================================================
-- After seeding, run these to verify:

-- Check user counts by role:
-- SELECT role, COUNT(*) FROM users GROUP BY role ORDER BY role;

-- Verify encryption (should show binary data, NOT readable text):
-- SELECT consultation_id, diagnosis FROM consultations LIMIT 3;

-- Verify decryption works:
-- SET @app_encryption_key = 'dev-secret-key-change-in-prod';
-- SET SESSION block_encryption_mode = 'aes-256-cbc';
-- SELECT consultation_id, decrypt_data(diagnosis) AS diagnosis FROM consultations;

-- Check audit trail was populated:
-- SELECT table_name, operation, COUNT(*) FROM school_clinic_audit.activity_log GROUP BY table_name, operation ORDER BY table_name;

-- Test view as student Juan (user_id=6):
-- SET @app_current_user_id = 6;
-- SET @app_current_role = 'student';
-- SET @app_encryption_key = 'dev-secret-key-change-in-prod';
-- SET SESSION block_encryption_mode = 'aes-256-cbc';
-- SELECT * FROM v_student_medical_history;  -- Should see only Juan's records

-- Test faculty view:
-- SET @app_current_user_id = 11;
-- SET @app_current_role = 'faculty';
-- SELECT * FROM v_faculty_clearance;  -- Should see clearance status only
-- ============================================================================
